module.exports = [
	{
		id_zule: "635e8cffedd89",
		title: "Demo_ZULE_1",
		description: "Demo description 1",
		channel_id: "5ece4797eaf5e",
		tags: ["action", "sports"],
		category: ["action", "sports"],
		views: { teaser: 1, zule: 0 },
		CBFC_rating: "U/A",
		reviews: { comments: [{ user_id: "g2pc28g0l9vgb2ii", name: "srklohith05", comment: "Hi" }, { user_id: "g2pc28g0l9vgb2ii", name: "srklohith05", comment: "Hi" }], likes: [] },
	},
	{
		id_zule: "635e8cffedd90",
		title: "Demo_ZULE_2",
		description: "Demo description 2",
		channel_id: "5ece4797eaf5e",
		tags: ["action", "sports"],
		category: ["action", "sports"],
		views: { teaser: 0, zule: 0 },
		CBFC_rating: "U/A",
		reviews: { comments: [], likes: ["g2pc28g0l9vgb2ii"] },
	},
	{
		id_zule: "635e8cffedd91",
		title: "Demo_ZULE_3",
		description: "Demo description 3",
		channel_id: "5ece4797eaf5e",
		tags: ["action", "sports"],
		category: ["action", "sports"],
		views: { teaser: 3, zule: 0 },
		CBFC_rating: "U/A",
		reviews: { comments: [], likes: [] },
	},
	{
		id_zule: "635e8cffedd92",
		title: "Demo_ZULE_4",
		description: "Demo description 4",
		channel_id: "5ece4797eaf5e",
		tags: ["action", "sports"],
		category: ["action", "sports"],
		views: { teaser: 0, zule: 0 },
		CBFC_rating: "U/A",
		reviews: { comments: [{ user_id: "1c4ovl9x0sxwu", name: "Solosanty2064", comment: "Op" }, { user_id: "g2pc28g0l9vgb2ii", name: "srklohith05", comment: "Hello" }], likes: ["g2pc28g0l9vgb2ii"] },
	},
	{
		id_zule: "635e8cffedd93",
		title: "Demo_ZULE_5",
		description: "Demo description 5",
		channel_id: "5ece4797eaf5e",
		tags: ["action", "sports"],
		category: ["action", "sports"],
		views: { teaser: 1, zule: 0 },
		CBFC_rating: "U/A",
		reviews: { comments: [], likes: ["1c4ovl9x0sxwu"] },
	},
]
