module.exports = [
	{
		id_zule: "1nom5p8dwadlff1jjy6",
		title: "Demovideo1",
		description: "Demo description 1",
		id_zuleSpot: "1nom5p8lff1jjy6",
		tags: ["Fight", "Crime"],
		genre: ["action", "sports"],
		views: { teaser: [], zule: [] },
		CBFC_rating: "U/A",
		reviews: { comments: [{ user_id: "g2pc28g0l9vgb2ii", name: "srklohith05", comment: "Hi" }, { user_id: "g2pc28g0l9vgb2ii", name: "srklohith05", comment: "Hi" }], likes: [] },
	},
	{
		id_zule: "1nom5p8dwlff1jjy6",
		title: "Demovideo2",
		description: "Demo description 2",
		id_zuleSpot: "1nom5p8lff1jjy6",
		tags: ["Fight", "Crime"],
		genre: ["action", "sports"],
		views: { teaser: [], zule: [] },
		CBFC_rating: "U/A",
		reviews: { comments: [{ user_id: "g2pc28g0l9vgb2ii", name: "srklohith05", comment: "Hi" }, { user_id: "g2pc28g0l9vgb2ii", name: "srklohith05", comment: "Hi" }], likes: [] },
	},
	{
		id_zule: "1m5p8dwadlff1jjy6",
		title: "Demovideo3",
		description: "Demo description 3",
		id_zuleSpot: "1nom5p8lff1jjy6",
		tags: ["Fight", "Crime"],
		genre: ["action", "sports"],
		views: { teaser: [], zule: [] },
		CBFC_rating: "U/A",
		reviews: { comments: [{ user_id: "g2pc28g0l9vgb2ii", name: "srklohith05", comment: "Hi" }, { user_id: "g2pc28g0l9vgb2ii", name: "srklohith05", comment: "Hi" }], likes: [] },
	},
	{
		id_zule: "1nom5p8dwadsff1jjy6",
		title: "Demovideo4",
		description: "Demo description 4",
		id_zuleSpot: "1nom5p8lff1jjy6",
		tags: ["Fight", "Crime"],
		genre: ["action", "sports"],
		views: { teaser: [], zule: [] },
		CBFC_rating: "U/A",
		reviews: { comments: [{ user_id: "g2pc28g0l9vgb2ii", name: "srklohith05", comment: "Hi" }, { user_id: "g2pc28g0l9vgb2ii", name: "srklohith05", comment: "Hi" }], likes: [] },
	},
	{
		id_zule: "1nom5p8dcsdwadlff1jjy6",
		title: "Demovideo5",
		description: "Demo description 5",
		id_zuleSpot: "1nom5p8lff1jjy6",
		tags: ["Fight", "Crime"],
		genre: ["action", "sports"],
		views: { teaser: [], zule: [] },
		CBFC_rating: "U/A",
		reviews: { comments: [{ user_id: "g2pc28g0l9vgb2ii", name: "srklohith05", comment: "Hi" }, { user_id: "g2pc28g0l9vgb2ii", name: "srklohith05", comment: "Hi" }], likes: [] },
	},
	{
		id_zule: "1nom5p8badlff1jjy6",
		title: "Demovideo6",
		description: "Demo description 6",
		id_zuleSpot: "1nom5p8lff1jjy6",
		tags: ["Fight", "Crime"],
		genre: ["action", "sports"],
		views: { teaser: [], zule: [] },
		CBFC_rating: "U/A",
		reviews: { comments: [{ user_id: "g2pc28g0l9vgb2ii", name: "srklohith05", comment: "Hi" }, { user_id: "g2pc28g0l9vgb2ii", name: "srklohith05", comment: "Hi" }], likes: [] },
	},
	{
		id_zule: "1nom5p8dwadlffdfjy6",
		title: "Demovideo7",
		description: "Demo description 7",
		id_zuleSpot: "1nom5p8lff1jjy6",
		tags: ["Fight", "Crime"],
		genre: ["action", "sports"],
		views: { teaser: [], zule: [] },
		CBFC_rating: "U/A",
		reviews: { comments: [{ user_id: "g2pc28g0l9vgb2ii", name: "srklohith05", comment: "Hi" }, { user_id: "g2pc28g0l9vgb2ii", name: "srklohith05", comment: "Hi" }], likes: [] },
	},
	{
		id_zule: "1nom5p8dwadlff1vsdy6",
		title: "Demovideo8",
		description: "Demo description 8",
		id_zuleSpot: "1nom5p8lff1jjy6",
		tags: ["Fight", "Crime"],
		genre: ["action", "sports"],
		views: { teaser: [], zule: [] },
		CBFC_rating: "U/A",
		reviews: { comments: [{ user_id: "g2pc28g0l9vgb2ii", name: "srklohith05", comment: "Hi" }, { user_id: "g2pc28g0l9vgb2ii", name: "srklohith05", comment: "Hi" }], likes: [] },
	},
	{
		id_zule: "1nom5fdswadlff1jjy6",
		title: "Demovideo9",
		description: "Demo description 9",
		id_zuleSpot: "1nom5p8lff1jjy6",
		tags: ["Fight", "Crime"],
		genre: ["action", "sports"],
		views: { teaser: [], zule: [] },
		CBFC_rating: "U/A",
		reviews: { comments: [{ user_id: "g2pc28g0l9vgb2ii", name: "srklohith05", comment: "Hi" }, { user_id: "g2pc28g0l9vgb2ii", name: "srklohith05", comment: "Hi" }], likes: [] },
	},
	{
		id_zule: "1nom5p8dwadlff1j",
		title: "Demovideo10",
		description: "Demo description 10",
		id_zuleSpot: "1nom5p8lff1jjy6",
		tags: ["Fight", "Crime"],
		genre: ["action", "sports"],
		views: { teaser: [], zule: [] },
		CBFC_rating: "U/A",
		reviews: { comments: [{ user_id: "g2pc28g0l9vgb2ii", name: "srklohith05", comment: "Hi" }, { user_id: "g2pc28g0l9vgb2ii", name: "srklohith05", comment: "Hi" }], likes: [] },
	},
]